include $(KERNEL_ROOT)/services/drivers/usb/components/usb.mk


usb_class = usbh_hub.o \
	    usbh_rndis.o \
	    rndis_host.o

usb_common = usb_common.o 

usb_core = usbh_core.o

usb_osal = usb_osal.o

usb_port = usb_hc_xhci.o


libserial = $(KERNEL_ROOT)/services/app/libserial.o
printf = $(KERNEL_ROOT)/services/app/printf.o
libmem = $(KERNEL_ROOT)/services/app/libmem.o
usyscall = $(KERNEL_ROOT)/services/app/usyscall.o 
arch_usyscall = $(KERNEL_ROOT)/services/app/arch_usyscall.o
session = $(KERNEL_ROOT)/services/app/session.o
libipc = $(KERNEL_ROOT)/services/app/libipc.o
libsem = $(KERNEL_ROOT)/services/app/libsemaphore.o




