include $(KERNEL_ROOT)/services/drivers/usb/components/usb.mk


usb_class = usbh_hub.o \
	    usbh_rndis.o \
	    rndis_host.o

usb_common = usb_common.o 

usb_core = usbh_core.o

usb_osal = usb_osal.o

usb_port = usb_hc_xhci.o



