
# usb_core = usbh_core.o


# libserial = $(KERNEL_ROOT)/services/app/libserial.o
# printf = $(KERNEL_ROOT)/services/app/printf.o
# libmem = $(KERNEL_ROOT)/services/app/libmem.o
# usyscall = $(KERNEL_ROOT)/services/app/usyscall.o 
# arch_usyscall = $(KERNEL_ROOT)/services/app/arch_usyscall.o
# session = $(KERNEL_ROOT)/services/app/session.o
# libipc = $(KERNEL_ROOT)/services/app/libipc.o
# libsem = $(KERNEL_ROOT)/services/app/libsemaphore.o

SRC_DIR := class core osal


include $(KERNEL_ROOT)/compiler.mk
