from building import *
import os

cwd = GetCurrentDir()

src = Glob('*.c')

group = DefineGroup('yolov2_json', src, depend = ['USING_YOLOV2_JSONPARSER', 'LIB_USING_CJSON'], CPPPATH = [cwd])

Return('group')
