SRC_FILES := ch32v20x_adc.c \
	ch32v20x_bkp.c \
	ch32v20x_can.c \
	ch32v20x_dbgmcu.c ch32v20x_dma.c \
	ch32v20x_exti.c \
	ch32v20x_flash.c \
	ch32v20x_gpio.c \
	ch32v20x_i2c.c ch32v20x_iwdg.c \
	ch32v20x_misc.c \
	ch32v20x_opa.c \
	ch32v20x_pwr.c \
	ch32v20x_rcc.c ch32v20x_rtc.c \
	ch32v20x_spi.c \
	ch32v20x_tim.c \
	ch32v20x_usart.c \
	ch32v20x_wwdg.c 

include $(KERNEL_ROOT)/compiler.mk