# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel character device drivers.
#

# obj-y              += src/config.o
# obj-y              += src/ipi_arm_mhu.o
# obj-y              += src/msg_queue.o


SRC_DIR := src test_xiuos
SRC_FILES := $(wildcard *.c)

include $(KERNEL_ROOT)/compiler.mk