SRC_FILES := stm32h7xx_hal.c \
			stm32h7xx_hal_uart.c \
			stm32h7xx_hal_cortex.c \
			stm32h7xx_hal_rcc.c \
			stm32h7xx_hal_rcc_ex.c \
			stm32h7xx_hal_gpio.c \
			stm32h7xx_hal_dma.c \
			stm32h7xx_hal_pwr.c \
			stm32h7xx_hal_pwr_ex.c \
			stm32h7xx_hal_uart_ex.c \
			stm32h7xx_hal_qspi.c 
include $(KERNEL_ROOT)/compiler.mk
