
SRC_DIR := board/rzv2l_smarc 
SRC_DIR += fsp/src/bsp/cmsis/Device/RENESAS/Source
SRC_DIR += fsp/src/bsp/mcu/all
SRC_DIR += fsp/src/r_ioport
SRC_DIR += fsp/src/r_mhu_ns
SRC_DIR += fsp/src/r_scif_uart
SRC_DIR += fsp/src/r_gtm
SRC_DIR += linaro

SRC_FILES := $(wildcard *.c)

include $(KERNEL_ROOT)/compiler.mk