SRC_FILES := aes.c aria.c asn1parse.c asn1write.c base64.c bignum.c certs.c cipher.c cmac.c ctr_drbg.c dhm.c ecp.c \
entropy.c files.txt md5.c md.c oid.c pem.c pk.c pkcs12.c pkcs5.c pkparse.c rsa.c rsa_internal.c sha1.c \
sha256.c ssl_cli.c ssl_srv.c ssl_tls.c

include $(KERNEL_ROOT)/compiler.mk