SRC_FILES :=
SRC_FILES += jerryscript/build/lib/libjerry-core.a \
             jerryscript/build/lib/libjerry-ext.a  \
             jerryscript/build/lib/libjerry-math.a

SRC_FILES += setjmp.S jerry_port.c jerry_main.c

include $(KERNEL_ROOT)/compiler.mk
