 SRC_FILES +=MQTTPacket.c\
			 MQTTConnectClient.c \
		     MQTTConnectServer.c \
			 MQTTDeserializePublish.c \
			 MQTTFormat.c \
			 MQTTSerializePublish.c \
			 MQTTSubscribeClient.c \
			 MQTTSubscribeServer.c \
			 MQTTUnsubscribeClient.c \
			 MQTTUnsubscribeServer.c \
			 transport.c

include $(KERNEL_ROOT)/compiler.mk