SRC_FILES := syscall.c \
	sys_spawn.c \
	sys_thread.c \
	sys_sleep.c \
	sys_yield.c \
	sys_register_as_server.c \
	sys_connect_session.c \
	sys_poll_session.c \
	sys_close_session.c \
	sys_register_irq.c \
	sys_exit.c \
	sys_state.c \
	sys_mmap.c \
	sys_kill.c \
	sys_semaphore.c \
	sys_wait_session.c

include $(KERNEL_ROOT)/compiler.mk
