# SRC_FILES := ping.c lwip_ping_demo.c lwip_config_demo.c lwip_dhcp_demo.c iperf.c http_test.c
SRC_FILES := ping.c lwip_ping_demo.c tcpecho_raw.c lwip_config_demo.c 

include $(KERNEL_ROOT)/compiler.mk
