SRC_FILES := \
	CH56x_bus8.c \
	CH56x_clk.c \
	CH56x_dvp.c \
	CH56x_ecdc.c \
	CH56x_emmc.c \
	CH56x_eth.c \
	CH56x_gpio.c \
	CH56x_hspi.c \
	CH56x_pwm.c \
	CH56x_pwr.c \
	CH56x_spi.c \
	CH56x_sys.c \
	CH56x_timer.c \
	CH56x_uart.c

include $(KERNEL_ROOT)/compiler.mk
