SRC_FILES := 	stm32g4xx_hal_cortex.c \
				stm32g4xx_hal_dma_ex.c \
				stm32g4xx_hal_dma.c \
				stm32g4xx_hal_fdcan.c \
				stm32g4xx_hal_gpio.c \
				stm32g4xx_hal_msp.c \
				stm32g4xx_hal_pcd_ex.c \
				stm32g4xx_hal_pcd.c \
				stm32g4xx_hal_pwr_ex.c \
				stm32g4xx_hal_pwr.c \
				stm32g4xx_hal_rcc_ex.c \
				stm32g4xx_hal_rcc.c \
				stm32g4xx_hal_spi.c \
				stm32g4xx_hal_uart_ex.c \
				stm32g4xx_hal_uart.c \
				stm32g4xx_hal.c \
				stm32g4xx_it.c \
				stm32g4xx_ll_usb.c

include $(KERNEL_ROOT)/compiler.mk